version: '2'
services:
    multilingualtester-app:
        image: multilingualtester
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://multilingualtester-mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    multilingualtester-mssql:
        extends:
            file: mssql.yml
            service: multilingualtester-mssql
